import { expect, test } from "@playwright/test";

test("parent registration, setup, login and child login coexist", async ({ page }) => {
  const email = `e2e-${crypto.randomUUID()}@example.test`;
  await page.goto("/top");
  await expect(page).toHaveURL("/");
  await page.getByRole("link", { name: "新規登録へ" }).click();
  await page.getByLabel("メールアドレス").fill(email);
  await page.getByLabel("パスワード").fill("test-password-123");
  await page.getByRole("button", { name: "登録する" }).click();
  await expect(page.getByRole("heading", { name: "初回セットアップ" })).toBeVisible();
  await page.getByLabel("子供の名前").fill("はな");
  await page.getByLabel("あいことば").fill("ひみつのことば");
  await page.getByRole("button", { name: "子供を作成する" }).click();
  await expect(page.getByRole("heading", { name: "子供のログインURL", exact: true })).toBeVisible();
  const childUrl = await page.locator('a[href*="/child/login/"]').first().getAttribute("href");
  expect(childUrl).toBeTruthy();
  await page.getByLabel("子供の名前").fill("ふたりめ");
  await page.getByRole("button", { name: "追加する", exact: true }).click();
  await expect(page.getByRole("heading", { name: "ふたりめ" })).toBeVisible();
  await page.getByRole("link", { name: "親のトップへ" }).click();
  await page.getByRole("button", { name: "ログアウト" }).click();
  await page.getByLabel("メールアドレス").fill(email);
  await page.getByLabel("パスワード").fill("test-password-123");
  await page.getByRole("button", { name: "ログイン", exact: true }).click();
  await expect(page.getByRole("heading", { name: "親のトップ" })).toBeVisible();
  await page.goto(childUrl!);
  await page.getByLabel("あいことば").fill("まちがったことば");
  await page.getByRole("button", { name: "ログイン", exact: true }).click();
  await expect(page.getByRole("alert")).toBeVisible();
  await page.getByLabel("あいことば").fill("ひみつのことば");
  await page.getByRole("button", { name: "ログイン", exact: true }).click();
  await expect(page.getByRole("heading", { name: "子供のトップ" })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("heading", { name: "子供のトップ" })).toBeVisible();
  await page.goto("/top");
  await expect(page.getByRole("heading", { name: "親のトップ" })).toBeVisible();
  await page.getByRole("button", { name: "ログアウト" }).click();
  await page.goto(childUrl!.replace("/child/login/", "/child/top/"));
  await expect(page.getByRole("heading", { name: "子供のトップ" })).toBeVisible();
});
